// packages/angular-renderer/src/lib/components/class-renderer.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, Input } from '@angular/core';
import type { ClassDiagram, ClassRelation } from '@typermaid/core';
import type { ClassDiagramAST } from '@typermaid/parser';
import { computeUnifiedDagreLayout } from '@typermaid/renderer-core';
import type { Theme } from '../services/theme.service';

/**
 * Extract string value from Content type
 */
function contentToString(content: string | { type: string; raw: string } | undefined): string | undefined {
  if (!content) return undefined;
  if (typeof content === 'string') return content;
  return content.raw;
}

@Component({
  selector: 'lyric-class-renderer',
  standalone: true,
  imports: [CommonModule],
  template: `
		<svg
			[attr.width]="layout().width"
			[attr.height]="layout().height"
			[attr.viewBox]="viewBox()"
		>
			<g>
				@for (edge of edges(); track edge.id) {
					<path
						[attr.d]="edge.path"
						[attr.stroke]="theme.colors.edge.stroke"
						[attr.stroke-width]="theme.colors.edge.strokeWidth"
						[attr.fill]="'none'"
						[attr.marker-end]="getMarker(edge.type)"
					/>
				}

				@for (cls of classes(); track cls.id) {
					<g [attr.transform]="'translate(' + cls.x + ',' + cls.y + ')'">
						<rect
							[attr.width]="cls.width"
							[attr.height]="cls.height"
							[attr.fill]="theme.colors.node.fill"
							[attr.stroke]="theme.colors.node.stroke"
							[attr.stroke-width]="theme.colors.node.strokeWidth"
						/>
						<text
							[attr.x]="cls.width / 2"
							[attr.y]="20"
							[attr.text-anchor]="'middle'"
							[attr.fill]="theme.colors.text"
							[style.font-family]="theme.fonts.primary"
							[style.font-weight]="'bold'"
						>
							{{ cls.name }}
						</text>
						<line
							[attr.x1]="0"
							[attr.y1]="30"
							[attr.x2]="cls.width"
							[attr.y2]="30"
							[attr.stroke]="theme.colors.node.stroke"
						/>
						@for (member of cls.members; track $index; let i = $index) {
							<text
								[attr.x]="10"
								[attr.y]="45 + i * 15"
								[attr.fill]="theme.colors.text"
								[style.font-family]="theme.fonts.monospace"
								[style.font-size.px]="11"
							>
								{{ member }}
							</text>
						}
					</g>
				}

				<defs>
					<marker id="inheritance" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto">
						<polygon points="0 0, 10 3, 0 6" [attr.fill]="'none'" [attr.stroke]="theme.colors.edge.stroke" />
					</marker>
					<marker id="composition" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto">
						<polygon points="0 3, 5 0, 10 3, 5 6" [attr.fill]="theme.colors.edge.stroke" />
					</marker>
				</defs>
			</g>
		</svg>
	`,
})
export class ClassRendererComponent {
  @Input({ required: true }) diagram!: ClassDiagramAST;
  @Input({ required: true }) theme!: Theme;

  layout = computed(() => {
    const nodes = this.diagram.diagram.classes.map((cls: ClassDiagram['classes'][0]) => ({
      id: cls.name,
      label: cls.name,
      width: 180,
      height: 80 + cls.members.length * 15,
    }));

    const edges = this.diagram.diagram.relations.map((rel) => {
      const labelStr = contentToString(rel.label);
      return {
        from: rel.from,
        to: rel.to,
        ...(labelStr ? { label: labelStr } : {}),
      };
    });

    return computeUnifiedDagreLayout(nodes, edges, {
      rankdir: 'TB',
      ranksep: 100,
      nodesep: 80,
    });
  });

  classes = computed(() => {
    return this.diagram.diagram.classes.map((cls: ClassDiagram['classes'][0]) => {
      const pos = this.layout().nodes.find((n) => n.id === cls.name);
      return {
        id: cls.name,
        name: cls.name,
        members: cls.members,
        x: pos?.x || 0,
        y: pos?.y || 0,
        width: pos?.width || 180,
        height: pos?.height || 80,
      };
    });
  });

  edges = computed(() => {
    return this.diagram.diagram.relations.map((rel: ClassRelation, i: number) => {
      const edgePoints = this.layout().edges.find((e) => e.from === rel.from && e.to === rel.to);
      const points = edgePoints?.points || [];
      const path =
        points.length > 0 && points[0]
          ? `M ${points[0].x} ${points[0].y} ${points.map((p: { x: number; y: number }, idx: number) => (idx > 0 ? `L ${p.x} ${p.y}` : '')).join(' ')}`
          : '';
      return {
        id: `${rel.from}-${rel.to}-${i}`,
        path,
        type: rel.relationType,
      };
    });
  });

  viewBox = computed(() => `0 0 ${this.layout().width} ${this.layout().height}`);

  getMarker(type: string): string {
    if (type === 'inheritance') return 'url(#inheritance)';
    if (type === 'composition') return 'url(#composition)';
    return '';
  }
}

// packages/react-renderer/src/components/ClassRenderer.tsx
import type { ClassDiagram, ClassMember } from '@typermaid/core';
import {
  computeUnifiedDagreLayout,
  measureTextCanvas,
  type UnifiedLayoutEdge,
  type UnifiedLayoutNode,
} from '@typermaid/renderer-core';
import type React from 'react';
import { useMemo } from 'react';
import type { Theme } from '../themes/types';

/**
 * Extract string value from Content type
 */
function contentToString(
  content: string | { type: string; raw: string } | undefined
): string | undefined {
  if (!content) return undefined;
  if (typeof content === 'string') return content;
  return content.raw;
}

interface ClassRendererProps {
  diagram: ClassDiagram;
  theme: Theme;
  width?: number;
  height?: number;
  interactive?: boolean;
}

export const ClassRenderer: React.FC<ClassRendererProps> = ({
  diagram,
  theme,
  width = 800,
  height = 600,
}) => {
  const classes = diagram.classes || [];
  const relationships = diagram.relations || [];

  // Font settings
  const headerFontSize = 16;
  const memberFontSize = 12;
  const padding = 20;
  const classHeaderHeight = 40;
  const itemHeight = 25;

  // Calculate class dimensions dynamically
  const classData = useMemo(() => {
    return classes.map((cls) => {
      const className = cls.name || cls.id;
      const headerMetrics = measureTextCanvas(className, headerFontSize, 'sans-serif', 'bold');

      const members = cls.members || [];
      const memberWidths = members.map((member) => {
        const memberText = `${member.visibility || '+'} ${member.name}: ${member.returnType || 'any'}`;
        const metrics = measureTextCanvas(memberText, memberFontSize, 'sans-serif', 'normal');
        return metrics.width;
      });

      const maxMemberWidth = memberWidths.length > 0 ? Math.max(...memberWidths) : 0;
      const classWidth = Math.max(headerMetrics.width, maxMemberWidth) + padding * 2;
      const classHeight = classHeaderHeight + members.length * itemHeight + 10;

      return {
        cls,
        width: Math.max(classWidth, 200),
        height: classHeight,
      };
    });
  }, [classes]);

  // Prepare nodes and edges for Dagre layout
  const layout = useMemo(() => {
    const nodes: UnifiedLayoutNode[] = classData.map(({ cls, width, height }) => ({
      id: cls.id,
      label: cls.name || cls.id,
      width,
      height,
    }));

    const edges: UnifiedLayoutEdge[] = relationships
      .map((rel): UnifiedLayoutEdge | null => {
        const labelStr = contentToString(rel.label);
        if (labelStr === undefined) {
          return {
            from: rel.from,
            to: rel.to,
          };
        }
        return {
          from: rel.from,
          to: rel.to,
          label: labelStr,
        };
      })
      .filter((edge): edge is UnifiedLayoutEdge => edge !== null);

    return computeUnifiedDagreLayout(nodes, edges, {
      rankdir: 'TB',
      ranksep: 100,
      nodesep: 80,
      marginx: 50,
      marginy: 50,
    });
  }, [classData, relationships]);

  // Generate path from points (polyline routing)
  const generatePath = (points: Array<{ x: number; y: number }>) => {
    if (points.length === 0) return '';
    const [first, ...rest] = points;
    if (!first) return '';
    const pathParts = [`M ${first.x} ${first.y}`];
    for (const point of rest) {
      pathParts.push(`L ${point.x} ${point.y}`);
    }
    return pathParts.join(' ');
  };

  return (
    <svg
      width={Math.max(width, layout.width)}
      height={Math.max(height, layout.height)}
      style={{ border: `1px solid ${theme.colors.border}`, background: theme.colors.background }}
    >
      {/* Render classes with Dagre positions */}
      {classData.map(({ cls, width: classWidth, height: classHeight }) => {
        const position = layout.nodes.find((n) => n.id === cls.id);
        if (!position) return null;

        const x = position.x - classWidth / 2;
        const y = position.y - classHeight / 2;
        const members = cls.members || [];

        return (
          <g key={cls.id}>
            <rect
              x={x}
              y={y}
              width={classWidth}
              height={classHeight}
              fill={theme.colors.node.fill}
              stroke={theme.colors.node.stroke}
              strokeWidth={2}
            />
            <rect
              x={x}
              y={y}
              width={classWidth}
              height={classHeaderHeight}
              fill={theme.colors.node.stroke}
              opacity={0.2}
            />
            <text
              x={position.x}
              y={y + classHeaderHeight / 2}
              fill={theme.colors.text}
              fontSize={16}
              fontWeight="bold"
              textAnchor="middle"
              dominantBaseline="middle"
            >
              {cls.name || cls.id}
            </text>

            <line
              x1={x}
              y1={y + classHeaderHeight}
              x2={x + classWidth}
              y2={y + classHeaderHeight}
              stroke={theme.colors.node.stroke}
              strokeWidth={1}
            />

            {members.map((member: ClassMember, i: number) => (
              <text
                key={`${cls.id}-member-${i}`}
                x={x + 10}
                y={y + classHeaderHeight + (i + 1) * itemHeight}
                fill={theme.colors.text}
                fontSize={12}
              >
                {member.visibility || '+'} {member.name}: {member.returnType || 'any'}
              </text>
            ))}
          </g>
        );
      })}

      {/* Render relationships with Dagre-routed edges */}
      {layout.edges.map((edge, index) => {
        const rel = relationships.find((r) => r.from === edge.from && r.to === edge.to);
        if (!rel) return null;

        const pathData = generatePath(edge.points);

        return (
          <path
            key={`${edge.from}-${edge.to}-${index}`}
            d={pathData}
            fill="none"
            stroke={theme.colors.edge.stroke}
            strokeWidth={2}
            markerEnd={rel.relationType === '<|--' ? 'url(#triangle)' : 'url(#arrow)'}
          />
        );
      })}

      <defs>
        <marker id="arrow" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto">
          <polygon points="0 0, 10 3, 0 6" fill={theme.colors.edge.stroke} />
        </marker>
        <marker id="triangle" markerWidth="10" markerHeight="10" refX="9" refY="5" orient="auto">
          <polygon
            points="0 0, 10 5, 0 10"
            fill="none"
            stroke={theme.colors.edge.stroke}
            strokeWidth={2}
          />
        </marker>
      </defs>
    </svg>
  );
};
