// packages/angular-renderer/src/lib/components/er-renderer.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, Input } from '@angular/core';
import type { ERDiagramAST } from '@typermaid/parser';
import { computeUnifiedDagreLayout } from '@typermaid/renderer-core';
import type { Theme } from '../services/theme.service';

/**
 * Extract string value from Content type
 */
function contentToString(
  content: string | { type: string; raw: string } | undefined
): string | undefined {
  if (!content) return undefined;
  if (typeof content === 'string') return content;
  return content.raw;
}

@Component({
  selector: 'lyric-er-renderer',
  standalone: true,
  imports: [CommonModule],
  template: `
		<svg
			[attr.width]="layout().width"
			[attr.height]="layout().height"
			[attr.viewBox]="viewBox()"
		>
			<g>
				@for (edge of edges(); track edge.id) {
					<path
						[attr.d]="edge.path"
						[attr.stroke]="theme.colors.edge.stroke"
						[attr.stroke-width]="theme.colors.edge.strokeWidth"
						[attr.fill]="'none'"
					/>
					@if (edge.label) {
						<text
							[attr.x]="edge.labelX"
							[attr.y]="edge.labelY"
							[attr.text-anchor]="'middle'"
							[attr.fill]="theme.colors.text"
							[style.font-family]="theme.fonts.primary"
							[style.font-size.px]="12"
						>
							{{ edge.label }}
						</text>
					}
				}

				@for (entity of entities(); track entity.id) {
					<g [attr.transform]="'translate(' + entity.x + ',' + entity.y + ')'">
						<rect
							[attr.width]="entity.width"
							[attr.height]="entity.height"
							[attr.fill]="theme.colors.node.fill"
							[attr.stroke]="theme.colors.node.stroke"
							[attr.stroke-width]="theme.colors.node.strokeWidth"
						/>
						<text
							[attr.x]="entity.width / 2"
							[attr.y]="20"
							[attr.text-anchor]="'middle'"
							[attr.fill]="theme.colors.text"
							[style.font-family]="theme.fonts.primary"
							[style.font-weight]="'bold'"
						>
							{{ entity.name }}
						</text>
						<line
							[attr.x1]="0"
							[attr.y1]="30"
							[attr.x2]="entity.width"
							[attr.y2]="30"
							[attr.stroke]="theme.colors.node.stroke"
						/>
						@for (attr of entity.attributes; track $index; let i = $index) {
							<text
								[attr.x]="10"
								[attr.y]="45 + i * 15"
								[attr.fill]="theme.colors.text"
								[style.font-family]="theme.fonts.monospace"
								[style.font-size.px]="11"
							>
								{{ attr }}
							</text>
						}
					</g>
				}
			</g>
		</svg>
	`,
})
export class ERRendererComponent {
  @Input({ required: true }) diagram!: ERDiagramAST;
  @Input({ required: true }) theme!: Theme;

  layout = computed(() => {
    const erDiagram = this.diagram.diagram;
    const nodes = erDiagram.entities.map((entity) => ({
      id: entity.name,
      label: entity.name,
      width: 180,
      height: 80 + entity.attributes.length * 15,
    }));

    const edges = erDiagram.relationships.map((rel) => {
      const labelStr = contentToString(rel.label);
      return {
        from: rel.from,
        to: rel.to,
        ...(labelStr ? { label: labelStr } : {}),
      };
    });

    return computeUnifiedDagreLayout(nodes, edges, {
      rankdir: 'LR',
      ranksep: 120,
      nodesep: 100,
    });
  });

  entities = computed(() => {
    const erDiagram = this.diagram.diagram;
    return erDiagram.entities.map((entity) => {
      const pos = this.layout().nodes.find((n) => n.id === entity.name);
      return {
        id: entity.name,
        name: entity.name,
        attributes: entity.attributes,
        x: pos?.x ?? 0,
        y: pos?.y ?? 0,
        width: pos?.width ?? 180,
        height: pos?.height ?? 80,
      };
    });
  });

  edges = computed(() => {
    const erDiagram = this.diagram.diagram;
    return erDiagram.relationships.map((rel, i: number) => {
      const edgePoints = this.layout().edges.find((e) => e.from === rel.from && e.to === rel.to);
      const points = edgePoints?.points ?? [];
      const firstPoint = points[0];
      const midPoint = points[Math.floor(points.length / 2)];
      const path =
        points.length > 0 && firstPoint
          ? `M ${firstPoint.x} ${firstPoint.y} ${points.map((p, idx: number) => (idx > 0 ? `L ${p.x} ${p.y}` : '')).join(' ')}`
          : '';
      const labelX = midPoint?.x ?? 0;
      const labelY = (midPoint?.y ?? 0) - 10;
      return {
        id: `${rel.from}-${rel.to}-${i}`,
        path,
        label: `${rel.fromCardinality} - ${rel.toCardinality}`,
        labelX,
        labelY,
      };
    });
  });

  viewBox = computed(() => `0 0 ${this.layout().width} ${this.layout().height}`);
}

// packages/react-renderer/src/components/ERRenderer.tsx
import type { ERAttribute, ERDiagram, EREntity } from '@typermaid/core';
import {
  computeUnifiedDagreLayout,
  measureTextCanvas,
  type UnifiedLayoutEdge,
  type UnifiedLayoutNode,
} from '@typermaid/renderer-core';
import type React from 'react';
import { useMemo } from 'react';
import type { Theme } from '../themes/types';

/**
 * Extract string value from Content type
 */
function contentToString(
  content: string | { type: string; raw: string } | undefined
): string | undefined {
  if (!content) return undefined;
  if (typeof content === 'string') return content;
  return content.raw;
}

interface ERRendererProps {
  diagram: ERDiagram;
  theme: Theme;
  width?: number;
  height?: number;
  interactive?: boolean;
}

export const ERRenderer: React.FC<ERRendererProps> = ({
  diagram,
  theme,
  width = 800,
  height = 600,
}) => {
  // Extract entities and relationships from diagram structure
  const explicitEntities = diagram.entities || [];
  const relationships = diagram.relationships || [];

  // Create entities from relationships if not explicitly defined
  const entities = useMemo(() => {
    const entityMap = new Map<string, EREntity>();

    // Add explicit entities
    for (const entity of explicitEntities) {
      entityMap.set(entity.name, entity);
    }

    // Add implicit entities from relationships
    for (const rel of relationships) {
      if (!entityMap.has(rel.from)) {
        entityMap.set(rel.from, { name: rel.from, attributes: [] });
      }
      if (!entityMap.has(rel.to)) {
        entityMap.set(rel.to, { name: rel.to, attributes: [] });
      }
    }

    return Array.from(entityMap.values());
  }, [explicitEntities, relationships]);

  // Font settings
  const headerFontSize = 14;
  const attributeFontSize = 11;
  const padding = 20;
  const entityHeaderHeight = 35;
  const attributeHeight = 22;

  // Calculate entity dimensions dynamically
  const entityData = useMemo(() => {
    return entities.map((entity) => {
      const headerMetrics = measureTextCanvas(entity.name, headerFontSize, 'sans-serif', 'bold');

      const attributes = entity.attributes || [];
      const attrWidths = attributes.map((attr) => {
        const attrText = `${attr.key ? '🔑 ' : ''}${attr.name} ${attr.type ? `(${attr.type})` : ''}`;
        const metrics = measureTextCanvas(attrText, attributeFontSize, 'sans-serif', 'normal');
        return metrics.width;
      });

      const maxAttrWidth = attrWidths.length > 0 ? Math.max(...attrWidths) : 0;
      const entityWidth = Math.max(headerMetrics.width, maxAttrWidth) + padding * 2;
      const entityHeight = entityHeaderHeight + attributes.length * attributeHeight + 10;

      return {
        entity,
        width: Math.max(entityWidth, 180),
        height: entityHeight,
      };
    });
  }, [entities]);

  // Prepare nodes and edges for Dagre layout
  const layout = useMemo(() => {
    const nodes: UnifiedLayoutNode[] = entityData.map(({ entity, width, height }) => ({
      id: entity.name,
      label: entity.name,
      width,
      height,
    }));

    const edges: UnifiedLayoutEdge[] = relationships
      .map((rel): UnifiedLayoutEdge | null => {
        const labelStr = contentToString(rel.label);
        if (labelStr === undefined) {
          return {
            from: rel.from,
            to: rel.to,
          };
        }
        return {
          from: rel.from,
          to: rel.to,
          label: labelStr,
        };
      })
      .filter((edge): edge is UnifiedLayoutEdge => edge !== null);

    return computeUnifiedDagreLayout(nodes, edges, {
      rankdir: 'LR', // ER diagrams typically flow left-to-right
      ranksep: 120,
      nodesep: 100,
      marginx: 50,
      marginy: 50,
    });
  }, [entityData, relationships]);

  // Generate path from points (polyline routing)
  const generatePath = (points: Array<{ x: number; y: number }>) => {
    if (points.length === 0) return '';
    const [first, ...rest] = points;
    if (!first) return '';
    const pathParts = [`M ${first.x} ${first.y}`];
    for (const point of rest) {
      pathParts.push(`L ${point.x} ${point.y}`);
    }
    return pathParts.join(' ');
  };

  return (
    <svg
      width={Math.max(width, layout.width)}
      height={Math.max(height, layout.height)}
      style={{ border: `1px solid ${theme.colors.border}`, background: theme.colors.background }}
    >
      {/* Render entities with Dagre positions */}
      {entityData.map(({ entity, width: entityWidth, height: entityHeight }) => {
        const position = layout.nodes.find((n) => n.id === entity.name);
        if (!position) return null;

        const x = position.x - entityWidth / 2;
        const y = position.y - entityHeight / 2;
        const attributes = entity.attributes || [];

        return (
          <g key={entity.name}>
            <rect
              x={x}
              y={y}
              width={entityWidth}
              height={entityHeight}
              fill={theme.colors.node.fill}
              stroke={theme.colors.node.stroke}
              strokeWidth={2}
              rx={5}
            />
            <rect
              x={x}
              y={y}
              width={entityWidth}
              height={entityHeaderHeight}
              fill={theme.colors.node.stroke}
              opacity={0.3}
              rx={5}
            />
            <text
              x={position.x}
              y={y + entityHeaderHeight / 2}
              fill={theme.colors.text}
              fontSize={14}
              fontWeight="bold"
              textAnchor="middle"
              dominantBaseline="middle"
            >
              {entity.name}
            </text>

            {attributes.map((attr: ERAttribute, i: number) => (
              <text
                key={`${entity.name}-attr-${i}`}
                x={x + 10}
                y={y + entityHeaderHeight + (i + 1) * attributeHeight}
                fill={theme.colors.text}
                fontSize={11}
              >
                {attr.key ? '🔑 ' : ''}
                {attr.name} {attr.type ? `(${attr.type})` : ''}
              </text>
            ))}
          </g>
        );
      })}

      {/* Render relationships with Dagre-routed edges */}
      {layout.edges.map((edge, index) => {
        const rel = relationships.find((r) => r.from === edge.from && r.to === edge.to);
        if (!rel) return null;

        const pathData = generatePath(edge.points);
        const midPoint = edge.points[Math.floor(edge.points.length / 2)];
        if (!midPoint) return null;

        return (
          <g key={`${edge.from}-${edge.to}-${index}`}>
            <path d={pathData} fill="none" stroke={theme.colors.edge.stroke} strokeWidth={2} />
            {edge.label && (
              <text
                x={midPoint.x}
                y={midPoint.y - 5}
                fill={theme.colors.text}
                fontSize={11}
                textAnchor="middle"
              >
                {edge.label}
              </text>
            )}
          </g>
        );
      })}
    </svg>
  );
};
