// packages/react-renderer/src/components/SequenceRenderer.tsx
import type { Participant, SequenceDiagram } from '@lyric-js/core';
import type React from 'react';
import type { Theme } from '../themes/types';

interface SequenceRendererProps {
  diagram: SequenceDiagram;
  theme: Theme;
  width?: number;
  height?: number;
  interactive?: boolean;
}

export const SequenceRenderer: React.FC<SequenceRendererProps> = ({
  diagram,
  theme,
  width = 800,
  height = 600,
}) => {
  const statements = diagram.diagram?.statements || [];

  interface MessageType {
    from: string;
    to: string;
    message: string;
    arrowType?: string;
  }

  // Extract participants from statements
  const participantsMap = new Map<string, Participant>();
  const messages: MessageType[] = [];

  for (const stmt of statements) {
    if (stmt.type === 'message') {
      if (!participantsMap.has(stmt.from)) {
        participantsMap.set(stmt.from, { id: stmt.from, label: stmt.from });
      }
      if (!participantsMap.has(stmt.to)) {
        participantsMap.set(stmt.to, { id: stmt.to, label: stmt.to });
      }
      messages.push({
        from: stmt.from,
        to: stmt.to,
        message: stmt.text || stmt.message,
        arrowType: stmt.arrowType,
      });
    }
  }

  const participants = Array.from(participantsMap.values());

  const participantWidth = 120;
  const participantHeight = 40;
  const participantSpacing = 60;
  const messageSpacing = 60;
  const topMargin = 50;
  const leftMargin = 50;

  const totalWidth =
    width || participants.length * (participantWidth + participantSpacing) + leftMargin * 2;
  const totalHeight =
    height || messages.length * messageSpacing + topMargin + participantHeight + 100;

  return (
    <svg
      width={totalWidth}
      height={totalHeight}
      style={{ border: `1px solid ${theme.colors.border}`, background: theme.colors.background }}
    >
      {participants.map((participant: Participant, index: number) => {
        const x = leftMargin + index * (participantWidth + participantSpacing);
        const y = topMargin;

        return (
          <g key={participant.id || index}>
            <rect
              x={x}
              y={y}
              width={participantWidth}
              height={participantHeight}
              fill={theme.colors.node.fill}
              stroke={theme.colors.node.stroke}
              strokeWidth={2}
              rx={5}
            />
            <text
              x={x + participantWidth / 2}
              y={y + participantHeight / 2}
              fill={theme.colors.text}
              fontSize={14}
              textAnchor="middle"
              dominantBaseline="middle"
            >
              {participant.label || participant.id}
            </text>
            <line
              x1={x + participantWidth / 2}
              y1={y + participantHeight}
              x2={x + participantWidth / 2}
              y2={totalHeight - 50}
              stroke={theme.colors.node.stroke}
              strokeWidth={1}
              strokeDasharray="5,5"
            />
          </g>
        );
      })}

      {messages.map((message: MessageType, index: number) => {
        const fromIndex = participants.findIndex((p: Participant) => p.id === message.from);
        const toIndex = participants.findIndex((p: Participant) => p.id === message.to);

        if (fromIndex === -1 || toIndex === -1) return null;

        const x1 =
          leftMargin + fromIndex * (participantWidth + participantSpacing) + participantWidth / 2;
        const x2 =
          leftMargin + toIndex * (participantWidth + participantSpacing) + participantWidth / 2;
        const y = topMargin + participantHeight + (index + 1) * messageSpacing;

        return (
          <g key={index}>
            <line
              x1={x1}
              y1={y}
              x2={x2}
              y2={y}
              stroke={theme.colors.edge.stroke}
              strokeWidth={2}
              markerEnd="url(#arrowhead)"
            />
            <text
              x={(x1 + x2) / 2}
              y={y - 5}
              fill={theme.colors.text}
              fontSize={12}
              textAnchor="middle"
            >
              {message.message || message.label}
            </text>
          </g>
        );
      })}

      <defs>
        <marker id="arrowhead" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto">
          <polygon points="0 0, 10 3, 0 6" fill={theme.colors.edge.stroke} />
        </marker>
      </defs>
    </svg>
  );
};

// packages/angular-renderer/src/lib/components/sequence-renderer.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, Input } from '@angular/core';
import type { Message, Participant } from '@typermaid/core';
import type { SequenceDiagramAST } from '@typermaid/parser';
import type { Theme } from '../services/theme.service';

@Component({
  selector: 'lyric-sequence-renderer',
  standalone: true,
  imports: [CommonModule],
  template: `
		<svg
			[attr.width]="width()"
			[attr.height]="height()"
			[attr.viewBox]="viewBox()"
		>
			<g>
				@for (participant of participants(); track participant.id; let i = $index) {
					<g>
						<rect
							[attr.x]="getParticipantX(i)"
							[attr.y]="topMargin"
							[attr.width]="participantWidth"
							[attr.height]="participantHeight"
							[attr.fill]="theme.colors.node.fill"
							[attr.stroke]="theme.colors.node.stroke"
							[attr.stroke-width]="theme.colors.node.strokeWidth"
						/>
						<text
							[attr.x]="getParticipantX(i) + participantWidth / 2"
							[attr.y]="topMargin + participantHeight / 2"
							[attr.text-anchor]="'middle'"
							[attr.dominant-baseline]="'middle'"
							[attr.fill]="theme.colors.text"
							[style.font-family]="theme.fonts.primary"
						>
							{{ participant.label }}
						</text>
						<line
							[attr.x1]="getParticipantX(i) + participantWidth / 2"
							[attr.y1]="topMargin + participantHeight"
							[attr.x2]="getParticipantX(i) + participantWidth / 2"
							[attr.y2]="totalHeight() - 20"
							[attr.stroke]="theme.colors.edge.stroke"
							[attr.stroke-dasharray]="'5,5'"
						/>
					</g>
				}

				@for (message of messages(); track $index; let i = $index) {
					<g>
						<line
							[attr.x1]="getMessageStartX(message)"
							[attr.y1]="getMessageY(i)"
							[attr.x2]="getMessageEndX(message)"
							[attr.y2]="getMessageY(i)"
							[attr.stroke]="theme.colors.edge.stroke"
							[attr.stroke-width]="theme.colors.edge.strokeWidth"
							[attr.marker-end]="'url(#arrowhead)'"
						/>
						<text
							[attr.x]="(getMessageStartX(message) + getMessageEndX(message)) / 2"
							[attr.y]="getMessageY(i) - 5"
							[attr.text-anchor]="'middle'"
							[attr.fill]="theme.colors.text"
							[style.font-family]="theme.fonts.primary"
							[style.font-size.px]="12"
						>
							{{ message.label }}
						</text>
					</g>
				}

				<defs>
					<marker
						id="arrowhead"
						markerWidth="10"
						markerHeight="10"
						refX="9"
						refY="3"
						orient="auto"
					>
						<polygon
							points="0 0, 10 3, 0 6"
							[attr.fill]="theme.colors.edge.stroke"
						/>
					</marker>
				</defs>
			</g>
		</svg>
	`,
})
export class SequenceRendererComponent {
  @Input({ required: true }) diagram!: SequenceDiagramAST;
  @Input({ required: true }) theme!: Theme;

  readonly topMargin = 50;
  readonly participantWidth = 120;
  readonly participantHeight = 40;
  readonly participantGap = 150;
  readonly messageGap = 60;
  readonly leftMargin = 50;

  participants = computed(() => {
    const seqDiagram = this.diagram.diagram;
    const statements = seqDiagram.statements;
    return statements.filter((s): s is Participant => s.type === 'participant');
  });
  messages = computed(() => {
    const seqDiagram = this.diagram.diagram;
    const statements = seqDiagram.statements;
    return statements.filter((s): s is Message => s.type === 'message');
  });

  width = computed(() => {
    const count = this.participants().length;
    return this.leftMargin * 2 + count * this.participantWidth + (count - 1) * this.participantGap;
  });

  totalHeight = computed(() => {
    const count = this.messages().length;
    return this.topMargin + this.participantHeight + count * this.messageGap + 40;
  });

  height = computed(() => this.totalHeight());
  viewBox = computed(() => `0 0 ${this.width()} ${this.height()}`);

  getParticipantX(index: number): number {
    return this.leftMargin + index * (this.participantWidth + this.participantGap);
  }

  getParticipantIndex(id: string): number {
    return this.participants().findIndex((p) => p.id === id);
  }

  getMessageY(index: number): number {
    return this.topMargin + this.participantHeight + (index + 1) * this.messageGap;
  }

  getMessageStartX(message: { from: string }): number {
    const index = this.getParticipantIndex(message.from);
    return this.getParticipantX(index) + this.participantWidth / 2;
  }

  getMessageEndX(message: { to: string }): number {
    const index = this.getParticipantIndex(message.to);
    return this.getParticipantX(index) + this.participantWidth / 2;
  }
}
