// packages/react-renderer/src/components/StateRenderer.tsx
import type { StateDiagram } from '@lyric-js/core';
import {
  computeUnifiedDagreLayout,
  measureTextCanvas,
  type UnifiedLayoutEdge,
  type UnifiedLayoutNode,
} from '@lyric-js/renderer-core';
import type React from 'react';
import { useMemo } from 'react';
import type { Theme } from '../themes/types';
import { ContentRenderer } from './ContentRenderer';

interface StateRendererProps {
  diagram: StateDiagram;
  theme: Theme;
  width?: number;
  height?: number;
  interactive?: boolean;
}

export const StateRenderer: React.FC<StateRendererProps> = ({
  diagram,
  theme,
  width = 800,
  height = 600,
}) => {
  const states = diagram.states || [];
  const transitions = diagram.transitions || [];

  // Font settings
  const labelFontSize = 14;
  const descFontSize = 10;
  const padding = 20;

  // Calculate state dimensions dynamically
  const stateData = useMemo(() => {
    return states.map((state) => {
      // Special sizes for START/END states (circles)
      if (state.type === 'START' || state.type === 'END') {
        return {
          state,
          width: 30,
          height: 30,
        };
      }

      const label = state.label || state.id;
      const labelText = typeof label === 'string' ? label : ''; // HTML content uses fixed size
      const descText = typeof state.description === 'string' ? state.description : '';

      const labelMetrics = labelText
        ? measureTextCanvas(labelText, labelFontSize, 'sans-serif', 'bold')
        : { width: 0, height: 0 };
      const descMetrics = descText
        ? measureTextCanvas(descText, descFontSize, 'sans-serif', 'normal')
        : { width: 0, height: 0 };

      const stateWidth = Math.max(labelMetrics.width, descMetrics.width) + padding * 2;
      const stateHeight = labelMetrics.height + descMetrics.height + padding * 2;

      return {
        state,
        width: Math.max(stateWidth, 140),
        height: Math.max(stateHeight, 60),
      };
    });
  }, [states]);

  // Prepare nodes and edges for Dagre layout
  const layout = useMemo(() => {
    const nodes: UnifiedLayoutNode[] = stateData.map(({ state, width, height }) => ({
      id: state.id,
      label: (typeof state.label === 'string' ? state.label : state.id) || state.id,
      width,
      height,
    }));

    const edges: UnifiedLayoutEdge[] = transitions
      .map((trans): UnifiedLayoutEdge | null => {
        const label = typeof trans.label === 'string' ? trans.label : undefined;
        if (label === undefined) {
          return {
            from: trans.from,
            to: trans.to,
          };
        }
        return {
          from: trans.from,
          to: trans.to,
          label,
        };
      })
      .filter((edge): edge is UnifiedLayoutEdge => edge !== null);

    return computeUnifiedDagreLayout(nodes, edges, {
      rankdir: 'LR', // State machines typically flow left-to-right
      ranksep: 80,
      nodesep: 60,
      marginx: 80,
      marginy: 80,
    });
  }, [stateData, transitions]);

  // Generate path from points (polyline routing)
  const generatePath = (points: Array<{ x: number; y: number }>) => {
    if (points.length === 0) return '';
    const [first, ...rest] = points;
    if (!first) return '';
    const pathParts = [`M ${first.x} ${first.y}`];
    for (const point of rest) {
      pathParts.push(`L ${point.x} ${point.y}`);
    }
    return pathParts.join(' ');
  };

  return (
    <svg
      width={Math.max(width, layout.width)}
      height={Math.max(height, layout.height)}
      style={{ border: `1px solid ${theme.colors.border}`, background: theme.colors.background }}
    >
      {/* Render states with Dagre positions */}
      {stateData.map(({ state, width: stateWidth, height: stateHeight }) => {
        const position = layout.nodes.find((n) => n.id === state.id);
        if (!position) return null;

        const isStart = state.type === 'START';
        const isEnd = state.type === 'END';

        if (isStart || isEnd) {
          return (
            <circle
              key={state.id}
              cx={position.x}
              cy={position.y}
              r={15}
              fill={isStart ? theme.colors.node.stroke : theme.colors.node.fill}
              stroke={theme.colors.node.stroke}
              strokeWidth={isEnd ? 4 : 2}
            />
          );
        }

        const x = position.x - stateWidth / 2;
        const y = position.y - stateHeight / 2;

        return (
          <g key={state.id}>
            <rect
              x={x}
              y={y}
              width={stateWidth}
              height={stateHeight}
              fill={theme.colors.node.fill}
              stroke={theme.colors.node.stroke}
              strokeWidth={2}
              rx={8}
            />
            {state.label ? (
              typeof state.label === 'string' ? (
                <text
                  x={position.x}
                  y={position.y}
                  fill={theme.colors.text}
                  fontSize={14}
                  fontWeight="bold"
                  textAnchor="middle"
                  dominantBaseline="middle"
                >
                  {state.label}
                </text>
              ) : (
                <ContentRenderer
                  content={state.label}
                  x={position.x}
                  y={position.y}
                  width={stateWidth - 10}
                  height={30}
                />
              )
            ) : (
              <text
                x={position.x}
                y={position.y}
                fill={theme.colors.text}
                fontSize={14}
                fontWeight="bold"
                textAnchor="middle"
                dominantBaseline="middle"
              >
                {state.id}
              </text>
            )}
            {state.description &&
              (typeof state.description === 'string' ? (
                <text
                  x={position.x}
                  y={position.y + 15}
                  fill={theme.colors.text}
                  fontSize={10}
                  textAnchor="middle"
                >
                  {state.description}
                </text>
              ) : (
                <ContentRenderer
                  content={state.description}
                  x={position.x}
                  y={position.y + 15}
                  width={stateWidth - 10}
                  height={20}
                />
              ))}
          </g>
        );
      })}

      {/* Render transitions with Dagre-routed edges */}
      {layout.edges.map((edge, index) => {
        const transition = transitions.find((t) => t.from === edge.from && t.to === edge.to);
        if (!transition) return null;

        const pathData = generatePath(edge.points);
        const midPoint = edge.points[Math.floor(edge.points.length / 2)];
        if (!midPoint) return null;

        return (
          <g key={`${edge.from}-${edge.to}-${index}`}>
            <path
              d={pathData}
              fill="none"
              stroke={theme.colors.edge.stroke}
              strokeWidth={2}
              markerEnd="url(#arrowhead-state)"
            />
            {transition.label &&
              (typeof transition.label === 'string' ? (
                <text
                  x={midPoint.x}
                  y={midPoint.y - 5}
                  fill={theme.colors.text}
                  fontSize={11}
                  textAnchor="middle"
                >
                  {transition.label}
                </text>
              ) : (
                <ContentRenderer
                  content={transition.label}
                  x={midPoint.x}
                  y={midPoint.y - 5}
                  width={120}
                  height={25}
                />
              ))}
          </g>
        );
      })}

      <defs>
        <marker
          id="arrowhead-state"
          markerWidth="10"
          markerHeight="10"
          refX="9"
          refY="3"
          orient="auto"
        >
          <polygon points="0 0, 10 3, 0 6" fill={theme.colors.edge.stroke} />
        </marker>
      </defs>
    </svg>
  );
};

// packages/angular-renderer/src/lib/components/state-renderer.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, Input } from '@angular/core';
import type { StateDiagramAST } from '@lyric-js/parser';
import { computeUnifiedDagreLayout } from '@lyric-js/renderer-core';
import type { Theme } from '../services/theme.service';

@Component({
  selector: 'lyric-state-renderer',
  standalone: true,
  imports: [CommonModule],
  template: `
		<svg
			[attr.width]="layout().width"
			[attr.height]="layout().height"
			[attr.viewBox]="viewBox()"
		>
			<g>
				@for (edge of edges(); track edge.id) {
					<path
						[attr.d]="edge.path"
						[attr.stroke]="theme.colors.edge.stroke"
						[attr.stroke-width]="theme.colors.edge.strokeWidth"
						[attr.fill]="'none'"
						[attr.marker-end]="'url(#arrowhead)'"
					/>
					@if (edge.label) {
						<text
							[attr.x]="edge.labelX"
							[attr.y]="edge.labelY"
							[attr.text-anchor]="'middle'"
							[attr.fill]="theme.colors.text"
							[style.font-family]="theme.fonts.primary"
							[style.font-size.px]="12"
						>
							{{ edge.label }}
						</text>
					}
				}

				@for (state of states(); track state.id) {
					<g [attr.transform]="'translate(' + state.x + ',' + state.y + ')'">
						@if (state.type === 'START' || state.type === 'END') {
							<circle
								[attr.r]="15"
								[attr.fill]="state.type === 'START' ? theme.colors.node.fill : theme.colors.node.stroke"
								[attr.stroke]="theme.colors.node.stroke"
								[attr.stroke-width]="theme.colors.node.strokeWidth"
							/>
						} @else {
							<rect
								[attr.x]="-state.width / 2"
								[attr.y]="-state.height / 2"
								[attr.width]="state.width"
								[attr.height]="state.height"
								[attr.rx]="5"
								[attr.fill]="theme.colors.node.fill"
								[attr.stroke]="theme.colors.node.stroke"
								[attr.stroke-width]="theme.colors.node.strokeWidth"
							/>
							<text
								[attr.x]="0"
								[attr.y]="0"
								[attr.text-anchor]="'middle'"
								[attr.dominant-baseline]="'middle'"
								[attr.fill]="theme.colors.text"
								[style.font-family]="theme.fonts.primary"
							>
								{{ state.label || state.id }}
							</text>
						}
					</g>
				}

				<defs>
					<marker
						id="arrowhead"
						markerWidth="10"
						markerHeight="10"
						refX="9"
						refY="3"
						orient="auto"
					>
						<polygon
							points="0 0, 10 3, 0 6"
							[attr.fill]="theme.colors.edge.stroke"
						/>
					</marker>
				</defs>
			</g>
		</svg>
	`,
})
export class StateRendererComponent {
  @Input({ required: true }) diagram!: StateDiagramAST;
  @Input({ required: true }) theme!: Theme;

  layout = computed(() => {
    const stateDiagram = this.diagram.diagram;
    const nodes = stateDiagram.states.map((state) => ({
      id: state.id,
      label: typeof state.label === 'string' ? state.label : state.id,
      width: state.type === 'START' || state.type === 'END' ? 30 : 120,
      height: state.type === 'START' || state.type === 'END' ? 30 : 60,
    }));

    const edges = stateDiagram.transitions.map((trans) => {
      const label = typeof trans.label === 'string' ? trans.label : undefined;
      return {
        from: trans.from,
        to: trans.to,
        ...(label ? { label } : {}),
      };
    });

    return computeUnifiedDagreLayout(nodes, edges, {
      rankdir: 'LR',
      ranksep: 80,
      nodesep: 60,
    });
  });

  states = computed(() => {
    const stateDiagram = this.diagram.diagram;
    return stateDiagram.states.map((state) => {
      const pos = this.layout().nodes.find((n) => n.id === state.id);
      return {
        id: state.id,
        type: state.type,
        label: typeof state.label === 'string' ? state.label : state.id,
        x: pos?.x ?? 0,
        y: pos?.y ?? 0,
        width: pos?.width ?? 120,
        height: pos?.height ?? 60,
      };
    });
  });

  edges = computed(() => {
    const stateDiagram = this.diagram.diagram;
    return stateDiagram.transitions.map((trans, i: number) => {
      const edgePoints = this.layout().edges.find(
        (e) => e.from === trans.from && e.to === trans.to
      );
      const points = edgePoints?.points ?? [];
      const firstPoint = points[0];
      const midPoint = points[Math.floor(points.length / 2)];
      const path =
        points.length > 0 && firstPoint
          ? `M ${firstPoint.x} ${firstPoint.y} ${points.map((p, idx: number) => (idx > 0 ? `L ${p.x} ${p.y}` : '')).join(' ')}`
          : '';
      const labelX = midPoint?.x ?? 0;
      const labelY = (midPoint?.y ?? 0) - 10;
      return {
        id: `${trans.from}-${trans.to}-${i}`,
        path,
        label: typeof trans.label === 'string' ? trans.label : undefined,
        labelX,
        labelY,
      };
    });
  });

  viewBox = computed(() => `0 0 ${this.layout().width} ${this.layout().height}`);
}
